version: '2'
networks:
  app-tier:
    driver: bridge
services:
  #web:
    #build:
      #context: .
      #dockerfile: Dockerfile
    #networks:
      #- app-tier
    #ports:
      #- "8006:8006"
    #expose:
      #- "8006"
    #depends_on:
      #- zookeeper
      #- kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    networks:
      - app-tier
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    expose:
      - "9093"
    networks:
      - app-tier
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "quickstart-events"
    depends_on:
      - zookeeper